/**
* @module SChainMainnet
* @description This file is entirely automatically generated by SChain TypeScript compiler
**/
  
import { Chain } from '@wagmi/core';

export const mainnet = {
  'round-hasty-alsafi': {
    id: 32429474,
    name: 'round-hasty-alsafi',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [ 'https://mainnet.skalenodes.com/v1/round-hasty-alsafi' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/round-hasty-alsafi' ]
      },
      public: {
        http: [ 'https://mainnet.skalenodes.com/v1/round-hasty-alsafi' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/round-hasty-alsafi' ]
      },
      filestorage: {
        http: [ 'https://mainnet.skalenodes.com/fs/round-hasty-alsafi' ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://round-hasty-alsafi.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'affectionate-immediate-pollux': {
    id: 1026062157,
    name: 'affectionate-immediate-pollux',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [
          'https://mainnet.skalenodes.com/v1/affectionate-immediate-pollux'
        ],
        webSocket: [
          'https://mainnet.skalenodes.com/v1/ws/affectionate-immediate-pollux'
        ]
      },
      public: {
        http: [
          'https://mainnet.skalenodes.com/v1/affectionate-immediate-pollux'
        ],
        webSocket: [
          'https://mainnet.skalenodes.com/v1/ws/affectionate-immediate-pollux'
        ]
      },
      filestorage: {
        http: [
          'https://mainnet.skalenodes.com/fs/affectionate-immediate-pollux'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://affectionate-immediate-pollux.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'gargantuan-wealthy-zosma': {
    id: 1931951519,
    name: 'gargantuan-wealthy-zosma',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [
          'https://mainnet.skalenodes.com/v1/gargantuan-wealthy-zosma'
        ],
        webSocket: [
          'https://mainnet.skalenodes.com/v1/ws/gargantuan-wealthy-zosma'
        ]
      },
      public: {
        http: [
          'https://mainnet.skalenodes.com/v1/gargantuan-wealthy-zosma'
        ],
        webSocket: [
          'https://mainnet.skalenodes.com/v1/ws/gargantuan-wealthy-zosma'
        ]
      },
      filestorage: {
        http: [
          'https://mainnet.skalenodes.com/fs/gargantuan-wealthy-zosma'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://gargantuan-wealthy-zosma.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'portly-passionate-sirius': {
    id: 393362594,
    name: 'portly-passionate-sirius',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [
          'https://mainnet.skalenodes.com/v1/portly-passionate-sirius'
        ],
        webSocket: [
          'https://mainnet.skalenodes.com/v1/ws/portly-passionate-sirius'
        ]
      },
      public: {
        http: [
          'https://mainnet.skalenodes.com/v1/portly-passionate-sirius'
        ],
        webSocket: [
          'https://mainnet.skalenodes.com/v1/ws/portly-passionate-sirius'
        ]
      },
      filestorage: {
        http: [
          'https://mainnet.skalenodes.com/fs/portly-passionate-sirius'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://portly-passionate-sirius.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'harsh-alsuhail': {
    id: 2747885419106851,
    name: 'harsh-alsuhail',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [ 'https://mainnet.skalenodes.com/v1/harsh-alsuhail' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/harsh-alsuhail' ]
      },
      public: {
        http: [ 'https://mainnet.skalenodes.com/v1/harsh-alsuhail' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/harsh-alsuhail' ]
      },
      filestorage: { http: [ 'https://mainnet.skalenodes.com/fs/harsh-alsuhail' ] }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://harsh-alsuhail.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'haunting-devoted-deneb': {
    id: 1032942172,
    name: 'haunting-devoted-deneb',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [ 'https://mainnet.skalenodes.com/v1/haunting-devoted-deneb' ],
        webSocket: [
          'https://mainnet.skalenodes.com/v1/ws/haunting-devoted-deneb'
        ]
      },
      public: {
        http: [ 'https://mainnet.skalenodes.com/v1/haunting-devoted-deneb' ],
        webSocket: [
          'https://mainnet.skalenodes.com/v1/ws/haunting-devoted-deneb'
        ]
      },
      filestorage: {
        http: [ 'https://mainnet.skalenodes.com/fs/haunting-devoted-deneb' ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://haunting-devoted-deneb.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'plain-rotanev': {
    id: 1622321144269118,
    name: 'plain-rotanev',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [ 'https://mainnet.skalenodes.com/v1/plain-rotanev' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/plain-rotanev' ]
      },
      public: {
        http: [ 'https://mainnet.skalenodes.com/v1/plain-rotanev' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/plain-rotanev' ]
      },
      filestorage: { http: [ 'https://mainnet.skalenodes.com/fs/plain-rotanev' ] }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://plain-rotanev.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'parallel-stormy-spica': {
    id: 1350216234,
    name: 'parallel-stormy-spica',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [ 'https://mainnet.skalenodes.com/v1/parallel-stormy-spica' ],
        webSocket: [
          'https://mainnet.skalenodes.com/v1/ws/parallel-stormy-spica'
        ]
      },
      public: {
        http: [ 'https://mainnet.skalenodes.com/v1/parallel-stormy-spica' ],
        webSocket: [
          'https://mainnet.skalenodes.com/v1/ws/parallel-stormy-spica'
        ]
      },
      filestorage: {
        http: [ 'https://mainnet.skalenodes.com/fs/parallel-stormy-spica' ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://parallel-stormy-spica.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'fit-betelgeuse': {
    id: 836542336838601,
    name: 'fit-betelgeuse',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [ 'https://mainnet.skalenodes.com/v1/fit-betelgeuse' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/fit-betelgeuse' ]
      },
      public: {
        http: [ 'https://mainnet.skalenodes.com/v1/fit-betelgeuse' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/fit-betelgeuse' ]
      },
      filestorage: { http: [ 'https://mainnet.skalenodes.com/fs/fit-betelgeuse' ] }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://fit-betelgeuse.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'wan-red-ain': {
    id: 1273227453,
    name: 'wan-red-ain',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [ 'https://mainnet.skalenodes.com/v1/wan-red-ain' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/wan-red-ain' ]
      },
      public: {
        http: [ 'https://mainnet.skalenodes.com/v1/wan-red-ain' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/wan-red-ain' ]
      },
      filestorage: { http: [ 'https://mainnet.skalenodes.com/fs/wan-red-ain' ] }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://wan-red-ain.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'turbulent-unique-scheat': {
    id: 278611351,
    name: 'turbulent-unique-scheat',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [ 'https://mainnet.skalenodes.com/v1/turbulent-unique-scheat' ],
        webSocket: [
          'https://mainnet.skalenodes.com/v1/ws/turbulent-unique-scheat'
        ]
      },
      public: {
        http: [ 'https://mainnet.skalenodes.com/v1/turbulent-unique-scheat' ],
        webSocket: [
          'https://mainnet.skalenodes.com/v1/ws/turbulent-unique-scheat'
        ]
      },
      filestorage: {
        http: [ 'https://mainnet.skalenodes.com/fs/turbulent-unique-scheat' ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://turbulent-unique-scheat.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'adorable-quaint-bellatrix': {
    id: 1909534317,
    name: 'adorable-quaint-bellatrix',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [
          'https://mainnet.skalenodes.com/v1/adorable-quaint-bellatrix'
        ],
        webSocket: [
          'https://mainnet.skalenodes.com/v1/ws/adorable-quaint-bellatrix'
        ]
      },
      public: {
        http: [
          'https://mainnet.skalenodes.com/v1/adorable-quaint-bellatrix'
        ],
        webSocket: [
          'https://mainnet.skalenodes.com/v1/ws/adorable-quaint-bellatrix'
        ]
      },
      filestorage: {
        http: [
          'https://mainnet.skalenodes.com/fs/adorable-quaint-bellatrix'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://adorable-quaint-bellatrix.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'wary-teeming-mizar': {
    id: 1494040293,
    name: 'wary-teeming-mizar',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [ 'https://mainnet.skalenodes.com/v1/wary-teeming-mizar' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/wary-teeming-mizar' ]
      },
      public: {
        http: [ 'https://mainnet.skalenodes.com/v1/wary-teeming-mizar' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/wary-teeming-mizar' ]
      },
      filestorage: {
        http: [ 'https://mainnet.skalenodes.com/fs/wary-teeming-mizar' ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://wary-teeming-mizar.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'light-vast-diphda': {
    id: 2139927552,
    name: 'light-vast-diphda',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [ 'https://mainnet.skalenodes.com/v1/light-vast-diphda' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/light-vast-diphda' ]
      },
      public: {
        http: [ 'https://mainnet.skalenodes.com/v1/light-vast-diphda' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/light-vast-diphda' ]
      },
      filestorage: {
        http: [ 'https://mainnet.skalenodes.com/fs/light-vast-diphda' ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://light-vast-diphda.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'green-giddy-denebola': {
    id: 1482601649,
    name: 'green-giddy-denebola',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [ 'https://mainnet.skalenodes.com/v1/green-giddy-denebola' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/green-giddy-denebola' ]
      },
      public: {
        http: [ 'https://mainnet.skalenodes.com/v1/green-giddy-denebola' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/green-giddy-denebola' ]
      },
      filestorage: {
        http: [ 'https://mainnet.skalenodes.com/fs/green-giddy-denebola' ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://green-giddy-denebola.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'elated-tan-skat': {
    id: 2046399126,
    name: 'elated-tan-skat',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [ 'https://mainnet.skalenodes.com/v1/elated-tan-skat' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/elated-tan-skat' ]
      },
      public: {
        http: [ 'https://mainnet.skalenodes.com/v1/elated-tan-skat' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/elated-tan-skat' ]
      },
      filestorage: { http: [ 'https://mainnet.skalenodes.com/fs/elated-tan-skat' ] }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://elated-tan-skat.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'honorable-steel-rasalhague': {
    id: 1564830818,
    name: 'honorable-steel-rasalhague',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [
          'https://mainnet.skalenodes.com/v1/honorable-steel-rasalhague'
        ],
        webSocket: [
          'https://mainnet.skalenodes.com/v1/ws/honorable-steel-rasalhague'
        ]
      },
      public: {
        http: [
          'https://mainnet.skalenodes.com/v1/honorable-steel-rasalhague'
        ],
        webSocket: [
          'https://mainnet.skalenodes.com/v1/ws/honorable-steel-rasalhague'
        ]
      },
      filestorage: {
        http: [
          'https://mainnet.skalenodes.com/fs/honorable-steel-rasalhague'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://honorable-steel-rasalhague.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'frayed-decent-antares': {
    id: 391845894,
    name: 'frayed-decent-antares',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [ 'https://mainnet.skalenodes.com/v1/frayed-decent-antares' ],
        webSocket: [
          'https://mainnet.skalenodes.com/v1/ws/frayed-decent-antares'
        ]
      },
      public: {
        http: [ 'https://mainnet.skalenodes.com/v1/frayed-decent-antares' ],
        webSocket: [
          'https://mainnet.skalenodes.com/v1/ws/frayed-decent-antares'
        ]
      },
      filestorage: {
        http: [ 'https://mainnet.skalenodes.com/fs/frayed-decent-antares' ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://frayed-decent-antares.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'curly-red-alterf': {
    id: 535219706,
    name: 'curly-red-alterf',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [ 'https://mainnet.skalenodes.com/v1/curly-red-alterf' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/curly-red-alterf' ]
      },
      public: {
        http: [ 'https://mainnet.skalenodes.com/v1/curly-red-alterf' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/curly-red-alterf' ]
      },
      filestorage: {
        http: [ 'https://mainnet.skalenodes.com/fs/curly-red-alterf' ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://curly-red-alterf.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  },
  'fussy-smoggy-megrez': {
    id: 644937893,
    name: 'fussy-smoggy-megrez',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SFuel', symbol: 'sFUEL' },
    rpcUrls: {
      default: {
        http: [ 'https://mainnet.skalenodes.com/v1/fussy-smoggy-megrez' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/fussy-smoggy-megrez' ]
      },
      public: {
        http: [ 'https://mainnet.skalenodes.com/v1/fussy-smoggy-megrez' ],
        webSocket: [ 'https://mainnet.skalenodes.com/v1/ws/fussy-smoggy-megrez' ]
      },
      filestorage: {
        http: [ 'https://mainnet.skalenodes.com/fs/fussy-smoggy-megrez' ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://fussy-smoggy-megrez.explorer.mainnet.skalenodes.com/'
      }
    },
    testnet: false
  }
} satisfies { [key: string]: Chain }
  