/**
* @module SChainStaging
* @description This file is entirely automatically generated by SChain TypeScript compiler
**/
  
import { Chain } from '@wagmi/core';

export const staging = {
  'staging-legal-crazy-castor': {
    id: 476158412,
    name: 'staging-legal-crazy-castor',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SKALE', symbol: 'SKL' },
    rpcUrls: {
      default: {
        http: [
          'https://staging-v3.skalenodes.com/v1/staging-legal-crazy-castor'
        ],
        webSocket: [
          'https://staging-v3.skalenodes.com/v1/ws/staging-legal-crazy-castor'
        ]
      },
      filestorage: {
        http: [
          'https://staging-v3.skalenodes.com/fs/staging-legal-crazy-castor'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://staging-legal-crazy-castor.explorer.staging-v3.skalenodes.com/'
      }
    }
  },
  'staging-purple-arctic-talitha': {
    id: 465227634,
    name: 'staging-purple-arctic-talitha',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SKALE', symbol: 'SKL' },
    rpcUrls: {
      default: {
        http: [
          'https://staging-v3.skalenodes.com/v1/staging-purple-arctic-talitha'
        ],
        webSocket: [
          'https://staging-v3.skalenodes.com/v1/ws/staging-purple-arctic-talitha'
        ]
      },
      filestorage: {
        http: [
          'https://staging-v3.skalenodes.com/fs/staging-purple-arctic-talitha'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://staging-purple-arctic-talitha.explorer.staging-v3.skalenodes.com/'
      }
    }
  },
  'staging-generous-flowery-elnath': {
    id: 1801222967,
    name: 'staging-generous-flowery-elnath',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SKALE', symbol: 'SKL' },
    rpcUrls: {
      default: {
        http: [
          'https://staging-v3.skalenodes.com/v1/staging-generous-flowery-elnath'
        ],
        webSocket: [
          'https://staging-v3.skalenodes.com/v1/ws/staging-generous-flowery-elnath'
        ]
      },
      filestorage: {
        http: [
          'https://staging-v3.skalenodes.com/fs/staging-generous-flowery-elnath'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://staging-generous-flowery-elnath.explorer.staging-v3.skalenodes.com/'
      }
    }
  },
  'staging-faint-slimy-achird': {
    id: 503129905,
    name: 'staging-faint-slimy-achird',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SKALE', symbol: 'SKL' },
    rpcUrls: {
      default: {
        http: [
          'https://staging-v3.skalenodes.com/v1/staging-faint-slimy-achird'
        ],
        webSocket: [
          'https://staging-v3.skalenodes.com/v1/ws/staging-faint-slimy-achird'
        ]
      },
      filestorage: {
        http: [
          'https://staging-v3.skalenodes.com/fs/staging-faint-slimy-achird'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://staging-faint-slimy-achird.explorer.staging-v3.skalenodes.com/'
      }
    }
  },
  'staging-perfect-parallel-gacrux': {
    id: 1370526269,
    name: 'staging-perfect-parallel-gacrux',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SKALE', symbol: 'SKL' },
    rpcUrls: {
      default: {
        http: [
          'https://staging-v3.skalenodes.com/v1/staging-perfect-parallel-gacrux'
        ],
        webSocket: [
          'https://staging-v3.skalenodes.com/v1/ws/staging-perfect-parallel-gacrux'
        ]
      },
      filestorage: {
        http: [
          'https://staging-v3.skalenodes.com/fs/staging-perfect-parallel-gacrux'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://staging-perfect-parallel-gacrux.explorer.staging-v3.skalenodes.com/'
      }
    }
  },
  'staging-severe-violet-wezen': {
    id: 1287568050,
    name: 'staging-severe-violet-wezen',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SKALE', symbol: 'SKL' },
    rpcUrls: {
      default: {
        http: [
          'https://staging-v3.skalenodes.com/v1/staging-severe-violet-wezen'
        ],
        webSocket: [
          'https://staging-v3.skalenodes.com/v1/ws/staging-severe-violet-wezen'
        ]
      },
      filestorage: {
        http: [
          'https://staging-v3.skalenodes.com/fs/staging-severe-violet-wezen'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://staging-severe-violet-wezen.explorer.staging-v3.skalenodes.com/'
      }
    }
  },
  'staging-utter-unripe-menkar': {
    id: 344106930,
    name: 'staging-utter-unripe-menkar',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SKALE', symbol: 'SKL' },
    rpcUrls: {
      default: {
        http: [
          'https://staging-v3.skalenodes.com/v1/staging-utter-unripe-menkar'
        ],
        webSocket: [
          'https://staging-v3.skalenodes.com/v1/ws/staging-utter-unripe-menkar'
        ]
      },
      filestorage: {
        http: [
          'https://staging-v3.skalenodes.com/fs/staging-utter-unripe-menkar'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://staging-utter-unripe-menkar.explorer.staging-v3.skalenodes.com/'
      }
    }
  },
  'staging-aware-chief-gianfar': {
    id: 1517929550,
    name: 'staging-aware-chief-gianfar',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SKALE', symbol: 'SKL' },
    rpcUrls: {
      default: {
        http: [
          'https://staging-v3.skalenodes.com/v1/staging-aware-chief-gianfar'
        ],
        webSocket: [
          'https://staging-v3.skalenodes.com/v1/ws/staging-aware-chief-gianfar'
        ]
      },
      filestorage: {
        http: [
          'https://staging-v3.skalenodes.com/fs/staging-aware-chief-gianfar'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://staging-aware-chief-gianfar.explorer.staging-v3.skalenodes.com/'
      }
    }
  },
  'staging-awesome-grave-subra': {
    id: 271642831,
    name: 'staging-awesome-grave-subra',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SKALE', symbol: 'SKL' },
    rpcUrls: {
      default: {
        http: [
          'https://staging-v3.skalenodes.com/v1/staging-awesome-grave-subra'
        ],
        webSocket: [
          'https://staging-v3.skalenodes.com/v1/ws/staging-awesome-grave-subra'
        ]
      },
      filestorage: {
        http: [
          'https://staging-v3.skalenodes.com/fs/staging-awesome-grave-subra'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://staging-awesome-grave-subra.explorer.staging-v3.skalenodes.com/'
      }
    }
  },
  'staging-famous-winding-tyl': {
    id: 1594672658,
    name: 'staging-famous-winding-tyl',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SKALE', symbol: 'SKL' },
    rpcUrls: {
      default: {
        http: [
          'https://staging-v3.skalenodes.com/v1/staging-famous-winding-tyl'
        ],
        webSocket: [
          'https://staging-v3.skalenodes.com/v1/ws/staging-famous-winding-tyl'
        ]
      },
      filestorage: {
        http: [
          'https://staging-v3.skalenodes.com/fs/staging-famous-winding-tyl'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://staging-famous-winding-tyl.explorer.staging-v3.skalenodes.com/'
      }
    }
  },
  'staging-lost-likely-aludra': {
    id: 876757986,
    name: 'staging-lost-likely-aludra',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SKALE', symbol: 'SKL' },
    rpcUrls: {
      default: {
        http: [
          'https://staging-v3.skalenodes.com/v1/staging-lost-likely-aludra'
        ],
        webSocket: [
          'https://staging-v3.skalenodes.com/v1/ws/staging-lost-likely-aludra'
        ]
      },
      filestorage: {
        http: [
          'https://staging-v3.skalenodes.com/fs/staging-lost-likely-aludra'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://staging-lost-likely-aludra.explorer.staging-v3.skalenodes.com/'
      }
    }
  },
  'staging-woozy-frizzy-merga': {
    id: 206279074,
    name: 'staging-woozy-frizzy-merga',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SKALE', symbol: 'SKL' },
    rpcUrls: {
      default: {
        http: [
          'https://staging-v3.skalenodes.com/v1/staging-woozy-frizzy-merga'
        ],
        webSocket: [
          'https://staging-v3.skalenodes.com/v1/ws/staging-woozy-frizzy-merga'
        ]
      },
      filestorage: {
        http: [
          'https://staging-v3.skalenodes.com/fs/staging-woozy-frizzy-merga'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://staging-woozy-frizzy-merga.explorer.staging-v3.skalenodes.com/'
      }
    }
  },
  'staging-weepy-fitting-caph': {
    id: 1019122823,
    name: 'staging-weepy-fitting-caph',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SKALE', symbol: 'SKL' },
    rpcUrls: {
      default: {
        http: [
          'https://staging-v3.skalenodes.com/v1/staging-weepy-fitting-caph'
        ],
        webSocket: [
          'https://staging-v3.skalenodes.com/v1/ws/staging-weepy-fitting-caph'
        ]
      },
      filestorage: {
        http: [
          'https://staging-v3.skalenodes.com/fs/staging-weepy-fitting-caph'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://staging-weepy-fitting-caph.explorer.staging-v3.skalenodes.com/'
      }
    }
  },
  'staging-costly-stale-albali': {
    id: 1277340369,
    name: 'staging-costly-stale-albali',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SKALE', symbol: 'SKL' },
    rpcUrls: {
      default: {
        http: [
          'https://staging-v3.skalenodes.com/v1/staging-costly-stale-albali'
        ],
        webSocket: [
          'https://staging-v3.skalenodes.com/v1/ws/staging-costly-stale-albali'
        ]
      },
      filestorage: {
        http: [
          'https://staging-v3.skalenodes.com/fs/staging-costly-stale-albali'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://staging-costly-stale-albali.explorer.staging-v3.skalenodes.com/'
      }
    }
  },
  'staging-fast-active-bellatrix': {
    id: 1351057110,
    name: 'staging-fast-active-bellatrix',
    network: 'skale',
    nativeCurrency: { decimals: 18, name: 'SKALE', symbol: 'SKL' },
    rpcUrls: {
      default: {
        http: [
          'https://staging-v3.skalenodes.com/v1/staging-fast-active-bellatrix'
        ],
        webSocket: [
          'https://staging-v3.skalenodes.com/v1/ws/staging-fast-active-bellatrix'
        ]
      },
      filestorage: {
        http: [
          'https://staging-v3.skalenodes.com/fs/staging-fast-active-bellatrix'
        ]
      }
    },
    blockExplorers: {
      default: {
        name: 'SKALE Explorer',
        url: 'https://staging-fast-active-bellatrix.explorer.staging-v3.skalenodes.com/'
      }
    }
  }
} satisfies { [key: string]: Chain }
  